/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DespatchRouteImport } from './routes/despatch'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as SellRouteImport } from './routes/sell'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDespatchersRouteImport } from './routes/admin.despatchers'
import { Route as AdminDispatchRouteImport } from './routes/admin.dispatch'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as DespatchIndexRouteImport } from './routes/despatch.index'
import { Route as DespatchApplyRouteImport } from './routes/despatch.apply'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as PaymentReferenceRouteImport } from './routes/payment.$reference'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as StoreSlugRouteImport } from './routes/store.$slug'
import { Route as VendorIndexRouteImport } from './routes/vendor.index'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as ApiPublicPaymentsWebhookGatewayRouteImport } from './routes/api/public/payments.webhook.$gateway'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DespatchRoute = DespatchRouteImport.update({
  id: '/despatch',
  path: '/despatch',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDespatchersRoute = AdminDespatchersRouteImport.update({
  id: '/despatchers',
  path: '/despatchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDispatchRoute = AdminDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const DespatchIndexRoute = DespatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DespatchRoute,
} as any)
const DespatchApplyRoute = DespatchApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => DespatchRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReferenceRoute = PaymentReferenceRouteImport.update({
  id: '/payment/$reference',
  path: '/payment/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendorRoute,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => VendorRoute,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => VendorRoute,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => VendorRoute,
} as any)
const ApiPublicPaymentsWebhookGatewayRoute =
  ApiPublicPaymentsWebhookGatewayRouteImport.update({
    id: '/api/public/payments/webhook/$gateway',
    path: '/api/public/payments/webhook/$gateway',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/despatch': typeof DespatchRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/nearby': typeof NearbyRoute
  '/sell': typeof SellRoute
  '/vendor': typeof VendorRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/admin/despatchers': typeof AdminDespatchersRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/despatch/apply': typeof DespatchApplyRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/$reference': typeof PaymentReferenceRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/despatch/': typeof DespatchIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/api/public/payments/webhook/$gateway': typeof ApiPublicPaymentsWebhookGatewayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/marketplace': typeof MarketplaceRoute
  '/nearby': typeof NearbyRoute
  '/sell': typeof SellRoute
  '/vendors': typeof VendorsRoute
  '/admin/despatchers': typeof AdminDespatchersRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/despatch/apply': typeof DespatchApplyRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/$reference': typeof PaymentReferenceRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/despatch': typeof DespatchIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/api/public/payments/webhook/$gateway': typeof ApiPublicPaymentsWebhookGatewayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/despatch': typeof DespatchRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/nearby': typeof NearbyRoute
  '/sell': typeof SellRoute
  '/vendor': typeof VendorRouteWithChildren
  '/vendors': typeof VendorsRoute
  '/admin/despatchers': typeof AdminDespatchersRoute
  '/admin/dispatch': typeof AdminDispatchRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/despatch/apply': typeof DespatchApplyRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/$reference': typeof PaymentReferenceRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/despatch/': typeof DespatchIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/api/public/payments/webhook/$gateway': typeof ApiPublicPaymentsWebhookGatewayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/despatch'
    | '/marketplace'
    | '/nearby'
    | '/sell'
    | '/vendor'
    | '/vendors'
    | '/admin/despatchers'
    | '/admin/dispatch'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/vendors'
    | '/despatch/apply'
    | '/orders/$id'
    | '/payment/$reference'
    | '/product/$id'
    | '/store/$slug'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/admin/'
    | '/despatch/'
    | '/vendor/'
    | '/api/public/payments/webhook/$gateway'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/marketplace'
    | '/nearby'
    | '/sell'
    | '/vendors'
    | '/admin/despatchers'
    | '/admin/dispatch'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/vendors'
    | '/despatch/apply'
    | '/orders/$id'
    | '/payment/$reference'
    | '/product/$id'
    | '/store/$slug'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/admin'
    | '/despatch'
    | '/vendor'
    | '/api/public/payments/webhook/$gateway'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/despatch'
    | '/marketplace'
    | '/nearby'
    | '/sell'
    | '/vendor'
    | '/vendors'
    | '/admin/despatchers'
    | '/admin/dispatch'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/vendors'
    | '/despatch/apply'
    | '/orders/$id'
    | '/payment/$reference'
    | '/product/$id'
    | '/store/$slug'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/admin/'
    | '/despatch/'
    | '/vendor/'
    | '/api/public/payments/webhook/$gateway'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  DespatchRoute: typeof DespatchRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  NearbyRoute: typeof NearbyRoute
  SellRoute: typeof SellRoute
  VendorRoute: typeof VendorRouteWithChildren
  VendorsRoute: typeof VendorsRoute
  OrdersIdRoute: typeof OrdersIdRoute
  PaymentReferenceRoute: typeof PaymentReferenceRoute
  ProductIdRoute: typeof ProductIdRoute
  StoreSlugRoute: typeof StoreSlugRoute
  ApiPublicPaymentsWebhookGatewayRoute: typeof ApiPublicPaymentsWebhookGatewayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despatch': {
      id: '/despatch'
      path: '/despatch'
      fullPath: '/despatch'
      preLoaderRoute: typeof DespatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/despatchers': {
      id: '/admin/despatchers'
      path: '/despatchers'
      fullPath: '/admin/despatchers'
      preLoaderRoute: typeof AdminDespatchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dispatch': {
      id: '/admin/dispatch'
      path: '/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AdminDispatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/despatch/': {
      id: '/despatch/'
      path: '/'
      fullPath: '/despatch/'
      preLoaderRoute: typeof DespatchIndexRouteImport
      parentRoute: typeof DespatchRoute
    }
    '/despatch/apply': {
      id: '/despatch/apply'
      path: '/apply'
      fullPath: '/despatch/apply'
      preLoaderRoute: typeof DespatchApplyRouteImport
      parentRoute: typeof DespatchRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$reference': {
      id: '/payment/$reference'
      path: '/payment/$reference'
      fullPath: '/payment/$reference'
      preLoaderRoute: typeof PaymentReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof VendorRoute
    }
    '/api/public/payments/webhook/$gateway': {
      id: '/api/public/payments/webhook/$gateway'
      path: '/api/public/payments/webhook/$gateway'
      fullPath: '/api/public/payments/webhook/$gateway'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDespatchersRoute: typeof AdminDespatchersRoute
  AdminDispatchRoute: typeof AdminDispatchRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDespatchersRoute: AdminDespatchersRoute,
  AdminDispatchRoute: AdminDispatchRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DespatchRouteChildren {
  DespatchApplyRoute: typeof DespatchApplyRoute
  DespatchIndexRoute: typeof DespatchIndexRoute
}

const DespatchRouteChildren: DespatchRouteChildren = {
  DespatchApplyRoute: DespatchApplyRoute,
  DespatchIndexRoute: DespatchIndexRoute,
}

const DespatchRouteWithChildren = DespatchRoute._addFileChildren(
  DespatchRouteChildren,
)

interface VendorRouteChildren {
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

const VendorRouteChildren: VendorRouteChildren = {
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  VendorIndexRoute: VendorIndexRoute,
}

const VendorRouteWithChildren =
  VendorRoute._addFileChildren(VendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  DespatchRoute: DespatchRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  NearbyRoute: NearbyRoute,
  SellRoute: SellRoute,
  VendorRoute: VendorRouteWithChildren,
  VendorsRoute: VendorsRoute,
  OrdersIdRoute: OrdersIdRoute,
  PaymentReferenceRoute: PaymentReferenceRoute,
  ProductIdRoute: ProductIdRoute,
  StoreSlugRoute: StoreSlugRoute,
  ApiPublicPaymentsWebhookGatewayRoute: ApiPublicPaymentsWebhookGatewayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
